name: main push


on:
  push:
    branches:
      - main
  # lancement manuel action
  workflow_dispatch:

jobs: 
  deploy:
    #needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy Toy

        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 95.216.126.102
          username: kaiser
          password: 1qazxsW@#Edc
          # host: ${{ secrets.STG_SSH_HOST }}
          # username: ${{ secrets.STG_SSH_USERNAME }}
          # password: ${{ secrets.STG_SSH_PASSWORD }}
          #key: ${{ secrets.SSH_KEY }}
          #port: ${{ secrets.SSH_PORT }}
          script: |

            cd /toy-document
            # git pull origin main
            # echo 'hello'
            # docker-compose -f docker-compose.yml up --build -d

