name: main push

on:
  push:
    branches:
      - main
  # lancement manuel action
  workflow_dispatch:

jobs: 
  deploy:
    #needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STG_SSH_HOST }}
          username: ${{ secrets.STG_SSH_USERNAME }}
          password: ${{ secrets.STG_SSH_PASSWORD }}
          #key: ${{ secrets.SSH_KEY }}
          #port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/daniconfigs-api
            # git pull origin staging
            # echo '${{ secrets.STG_ENV_CONFIG_JSON }}' > .env
            # docker-compose -f docker-compose.yml up --build -d