<<<<<<< HEAD
name: PUSH TO STAGING
=======
name: main push
>>>>>>> c50894377a79678ed369c2a4841d86a7cb30c6a9

on:
  push:
    branches:
      - main
  # lancement manuel action
  workflow_dispatch:

jobs: 
  deploy:
    #needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy Toy

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STG_SSH_HOST }}
          username: ${{ secrets.STG_SSH_USERNAME }}
          password: ${{ secrets.STG_SSH_PASSWORD }}
          #key: ${{ secrets.SSH_KEY }}
          #port: ${{ secrets.SSH_PORT }}
          script: |

            cd /toy-document
            git pull origin main
            echo 'hello'
            # docker-compose -f docker-compose.yml up --build -d

